#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangfire.QuickJump.Dashboard
{
    
    #line 2 "..\..\Dashboard\RecurringJobDetails.cshtml"
    using System;
    
    #line default
    #line hidden
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 3 "..\..\Dashboard\RecurringJobDetails.cshtml"
    using Hangfire.Dashboard;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Dashboard\RecurringJobDetails.cshtml"
    using Hangfire.Dashboard.Pages;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Dashboard\RecurringJobDetails.cshtml"
    using Hangfire.QuickJump.Utils;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Dashboard\RecurringJobDetails.cshtml"
    using Hangfire.Storage;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class RecurringJobDetails : RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");








            
            #line 8 "..\..\Dashboard\RecurringJobDetails.cshtml"
  
    RecurringJobDto recurringJob = null;

    using (var connection = Storage.GetConnection())
    {
        recurringJob = connection.GetRecurringJobDto(RecurringJobId);
    }

    Layout = new LayoutPage(String.Format("Recurring Job '{0}'", RecurringJobId));


            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 19 "..\..\Dashboard\RecurringJobDetails.cshtml"
 if (recurringJob == null)
{

            
            #line default
            #line hidden
WriteLiteral("    <div class=\"alert alert-warning\">Couldn\'t find recurring job \'");


            
            #line 21 "..\..\Dashboard\RecurringJobDetails.cshtml"
                                                             Write(RecurringJobId);

            
            #line default
            #line hidden
WriteLiteral("\'.</div>\r\n");


            
            #line 22 "..\..\Dashboard\RecurringJobDetails.cshtml"
}
else
{

            
            #line default
            #line hidden
WriteLiteral("    <div>\r\n        Hello world, ");


            
            #line 26 "..\..\Dashboard\RecurringJobDetails.cshtml"
                Write(RecurringJobId);

            
            #line default
            #line hidden
WriteLiteral("!\r\n        ");


            
            #line 27 "..\..\Dashboard\RecurringJobDetails.cshtml"
   Write(recurringJob);

            
            #line default
            #line hidden
WriteLiteral("?.Cron\r\n    </div>\r\n");


            
            #line 29 "..\..\Dashboard\RecurringJobDetails.cshtml"
}

            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
