# AppVeyor CI build file, https://ci.appveyor.com/project/odinserj/hangfire
# Don't edit manually! Use `build.bat version` command instead!
version: 0.1.0-build-0{build}

os: Visual Studio 2017
build_script: build.bat pack
test: off
artifacts:
  - path: 'build\**\*.nupkg'
  - path: 'build\**\*.zip'
